CLIP:
  SAVED_DIR: "PA100k_Checkpoint.pth"
  PRETRAINED_ViT_NAME: "ViT-L/14"
  VISUAL_PROMPT_NUM: 50
  TEXT_PROMPT_NUM: 3
  USE_GLOBAL_LOCAL_SIMILARITY: True #https://openaccess.thecvf.com/content/ICCV2023/html/Abdelfattah_CDUL_CLIP-Driven_Unsupervised_Learning_for_Multi-Label_Image_Classification_ICCV_2023_paper.html
  USE_TEXT_PROMPT: True
  GLOBAL_LOCAL_SIMILARITY_THRESHOLD: 0.5
  USE_REGION_SPLIT: True #Region-aware Prompt parameters
  REGION_SPLIT_NUM: 4 #Region-aware Prompt parameters
  REGION_SPLIT_OVERLAPPING_ROW_NUM: 2 #Region-aware Prompt parameters
  VISUAL_PROMPT_DEPTH: 24
  USE_VISUAL_MASK: True
  PARAMETERS_TO_BE_UPDATED: ["prompt_deep", "prompt_text_deep", "part_class_embedding", "agg_bn", "softmax_model"]

TRAINER:
  ACCELERATOR: "gpu"
  DEVICES: 1

MODEL:
  NAME: 'base'
  ATTRIBUTE_NUM: 15
  PRETRAINED_DIR: 'data/jx_vit_base_p16_224-80ecf9dd.pth' #ViT
  TEXT_DIMENSION: 768
  USE_MULTIMODAL_TRANSFORMER: True
  MM_LAYERS_NUM: 1
  PARAMETERS_TO_BE_UPDATED: ["word_embed", "weight_layer", "bn", "norm"]
  LOSS: "Weighted Cross Entropy"

DATASET:
  NAMES: 'PPEmultilabelDataset'
  TRAIN_LABEL_PATH: "data/labels/attribute_label_split_train_0303_sgIsEa.json"
  VAL_LABEL_PATH: "data/labels/attribute_label_test_0303_sgIsEa.json"
  TEST_LABEL_PATH: "data/labels/attribute_label_test_0303_sgIsEa.json"
  TRAIN_LABEL_MAT: "dataset/train_labels.pkl"
  VAL_LABEL_MAT: "dataset/val_labels.pkl"
  INPUT_IMG_SIZE: [224,224]
  RANDOM_ROTATION_RANGE: [-90, 90]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.0
  TRAIN_LABEL_MATRIX_DIR: 'data/label_mat/train_labels.pkl'
  TEST_LABEL_MATRIX_DIR: 'data/label_mat/val_labels.pkl'

HYPERPARAM:
  # OPTIMIZER_NAME: 'AdamW'
  # SCHEDULER_NAME: 'CosineAnnealingLR'
  BATCH_SIZE: 16
  LR: 0.008
  CLIP_LR: 0.004
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  CLIP_WEIGHT_DECAY: 0.0001
  NUM_EPOCH: 50
  WARMUP_EPOCH: 5

ATTRIBUTES: [
    'A person wearing a gown completely',
    'A person not wearing a gown',
    'A person wearing a gown incorrectly',
    'A person wearing a helmet',
    'A person wearing goggles',
    'A person wearing a face shield',
    'A person not wearing eyewear',
    'A person wearing an N95 mask',
    'A person wearing a regular mask',
    'A person not wearing a mask',
    'A person with two visible hands wearing two gloves',
    'A person with one visible hand wearing one glove',
    'A person with two visible hands wearing no gloves',
    'A person with one visible glove, the other hand not visible',
    'A person with one visible hand, the other hand not visible'
]